# Generated by Django 3.2.5 on 2021-10-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20211030_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygroup',
            name='join_click',
            field=models.BooleanField(default=False),
        ),
    ]
