# Generated by Django 3.2.5 on 2021-10-30 12:32

import basic_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_mygroup_join_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='curr_user',
            field=models.CharField(default=basic_app.models.User, max_length=256),
        ),
    ]
