# Generated by Django 3.2.5 on 2021-10-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_mypost_curr_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='curr_user',
            field=models.CharField(max_length=256),
        ),
    ]
