# Generated by Django 3.2.5 on 2021-10-30 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_alter_mypost_curr_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
