# Generated by Django 3.2.5 on 2021-10-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_mypost_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mygroup',
            name='post_count',
        ),
        migrations.AddField(
            model_name='mypost',
            name='created_by',
            field=models.CharField(default=',', max_length=100),
        ),
        migrations.AddField(
            model_name='mypost',
            name='post_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
